name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build Project
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet test --no-build --verbosity normal
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libv64core-${{ github.run_number }}
        path: D:\a\LibV64Core\LibV64Core\LibV64Core\bin\Release\net6.0\
